"""
Project: Amazon India Profitability Calculator (2026 Edition)
Author: Kaitou-debug
Description: 
    A Python automation tool that generates a financial model for e-commerce sellers.
    It calculates Net Profit, Margins, and GST Input Credit based on the latest 
    Amazon India fee structures (Referral, Closing, and Weight Handling fees).
    
    Output: An interactive Excel dashboard (.xlsx) with embedded formulas.
"""

import pandas as pd
import xlsxwriter
import os

def generate_amazon_model():
    """
    Main function to generate the Excel Financial Model.
    """
    # 1. Define the filename
    file_name = "Mivera_Amazon_Profit_Calculator_2026.xlsx"
    print(f"Initializing generation for: {file_name}...")

    # 2. Create Dummy Data (Scenarios for the user to test)
    data = [
        ["Bamboo Toothbrush", 50, 199, 0.12, 200, "National"],  # Low Ticket (<300)
        ["Wooden Desk Tray", 350, 899, 0.12, 800, "National"],  # Standard Item
        ["Gaming Mouse Pad", 150, 499, 0.15, 400, "National"],  # Mid Range
    ]

    columns = [
        "Product Name", "Buying Price (₹)", "Selling Price (₹)", 
        "Ref Fee % (Input)", "Weight (gms)", "Region"
    ]

    df = pd.DataFrame(data, columns=columns)

    # 3. Initialize Excel Writer with XlsxWriter engine
    writer = pd.ExcelWriter(file_name, engine="xlsxwriter")
    df.to_excel(writer, sheet_name="Profit_Calculator", index=False, startrow=1)

    # 4. Get Workbook and Worksheet objects for formatting
    workbook = writer.book
    worksheet = writer.sheets["Profit_Calculator"]

    # 5. Define Professional Formats (Mivera Brand Colors)
    header_fmt = workbook.add_format({
        'bold': True, 'text_wrap': True, 'valign': 'top', 'fg_color': '#FF9900', 
        'border': 1, 'font_color': 'white', 'align': 'center'
    })
    currency_fmt = workbook.add_format({'num_format': '₹#,##0.00'})
    percent_fmt = workbook.add_format({'num_format': '0%'})
    green_fmt = workbook.add_format({'bg_color': '#C6EFCE', 'font_color': '#006100', 'num_format': '₹#,##0.00'}) # Profit Green
    
    # Write Headers
    for col_num, value in enumerate(columns):
        worksheet.write(0, col_num, value, header_fmt)

    # Add Calculated Column Headers
    calc_headers = [
        "Ref Fee (₹)", "Closing Fee (₹)", "Shipping Fee (₹)", 
        "GST (18%)", "Total Deduction", "Bank Settlement", 
        "NET PROFIT (₹)", "Margin (%)"
    ]

    for col_num, value in enumerate(calc_headers):
        worksheet.write(0, len(columns) + col_num, value, header_fmt)

    # 6. Inject Logic (Live Excel Formulas)
    print("Injecting financial formulas...")
    for row_num in range(1, 101):
        row = row_num + 1
        
        # A. Referral Fee Logic (0% if price < 300, else %)
        worksheet.write_formula(row_num, 6, f'=IF(C{row}<300, 0, C{row}*D{row})', currency_fmt)
        
        # B. Closing Fee Logic (Standard Slabs)
        worksheet.write_formula(row_num, 7, f'=IF(C{row}<=250, 5, IF(C{row}<=500, 9, IF(C{row}<=1000, 30, 56)))', currency_fmt)
        
        # C. Shipping Logic (Simplified Estimate)
        worksheet.write_formula(row_num, 8, f'=IF(E{row}<=500, 65, 85)', currency_fmt)
        
        # D. Taxes & Totals
        worksheet.write_formula(row_num, 9, f'=0.18*(G{row}+H{row}+I{row})', currency_fmt)
        worksheet.write_formula(row_num, 10, f'=G{row}+H{row}+I{row}+J{row}', currency_fmt)
        worksheet.write_formula(row_num, 11, f'=C{row}-K{row}', currency_fmt)
        worksheet.write_formula(row_num, 12, f'=L{row}-B{row}', green_fmt)
        worksheet.write_formula(row_num, 13, f'=IFERROR(M{row}/C{row}, 0)', percent_fmt)

    # 7. Add Branding Footer
    worksheet.merge_range('A105:F105', "Tool Generated by Kaitou-debug | Mivera Tech Solutions", workbook.add_format({'bold': True}))
    
    # Adjust Column Widths
    worksheet.set_column('A:A', 20)
    worksheet.set_column('G:N', 15)

    writer.close()
    print(f"SUCCESS: '{file_name}' has been generated in {os.getcwd()}")

if __name__ == "__main__":
    generate_amazon_model()